fix: modify the .yml file code logic

diff --git a/.github/workflows/pr_title_validation.yml b/.github/workflows/pr_title_validation.yml
--- a/.github/workflows/pr_title_validation.yml
+++ b/.github/workflows/pr_title_validation.yml
@@ -1,6 +1,6 @@
 name: "PR Title Checker"
 on:
-  pull_request_target:
+  pull_request:
     types:
       - opened
       - edited
@@ -13,8 +13,26 @@ jobs:
   check:
     runs-on: ubuntu-latest
     steps:
-      - uses: thehanimo/pr-title-checker@v1.4.1
-        with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          pass_on_octokit_error: false
-          configuration_path: .github/pr-title-checker-config.json
+      - name: Check out repository
+        uses: actions/checkout@v2
+
+      - name: Get PR Title
+        id: get_pr_title
+        run: echo "::set-output name=title::${{ github.event.pull_request.title }}"
+
+      - name: Validate PR Title
+        id: validate_title
+        run: |
+          PR_TITLE="${{ steps.get_pr_title.outputs.title }}"
+          echo "PR title: $PR_TITLE"
+          if [[ "$PR_TITLE" =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|style|test|sample):\ [a-zA-Z0-9\ ]{0,50}$ ]]; then
+            echo "PR title is as per standards: $PR_TITLE"
+            echo "::set-output name=result::success"
+          else
+            echo "PR title is not as per standards. PR title must start with one of the following prefixes: build, chore, ci, docs, feat, fix, perf, refactor, style, test, sample. PR title content must not exceed 50 characters. Your PR title was: $PR_TITLE"
+            echo "::set-output name=result::failure"
+          fi
+
+      - name: Set PR Title Check Result
+        if: steps.validate_title.outputs.result == 'failure'
+        run: exit 1
